consulta_sql = '''
SELECT 
	C.PROFISSAO,
	C.TEMPOPROFISSAO,
	C.RENDA,
	C.TIPORESIDENCIA,
	C.ESCOLARIDADE,
	C.SCORE,
	EXTRACT (YEAR FROM AGE(C.DATANASCIMENTO)) AS IDADE,
	C.DEPENDENTES,
	C.ESTADOCIVIL,
	PF.NOMECOMERCIAL,
	PC.VALORSOLICITADO,
	PC.VALORTOTALBEM,
	CASE
		WHEN COUNT(P.STATUS) FILTER (WHERE P.STATUS = 'Vencido') > 0 THEN 'Ruim'
	ELSE 'Bom'
	END CLASSE
	FROM CLIENTES C
INNER JOIN PEDIDOCREDITO PC ON C.CLIENTEID = PC.CLIENTEID
LEFT JOIN PARCELASCREDITO P ON PC.SOLICITACAOID = P.SOLICITACAOID
INNER JOIN PRODUTOSFINANCIADOS PF ON PC.PRODUTOID = PF.PRODUTOID
WHERE PC.STATUS = 'Aprovado'
GROUP BY C.CLIENTEID, PF.NOMECOMERCIAL, PC.VALORSOLICITADO, PC.VALORTOTALBEM;
'''